// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGnmSdcYDr9JKjo7ZeYAsYWycT0CfNCyI',
    appId: '1:839286460671:web:938bede810a1838f647cca',
    messagingSenderId: '839286460671',
    projectId: 'finalyearproject-b2776',
    authDomain: 'finalyearproject-b2776.firebaseapp.com',
    databaseURL: 'https://finalyearproject-b2776-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finalyearproject-b2776.firebasestorage.app',
    measurementId: 'G-2GQM8674V7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFd5vjewqBsb9DDNr-c29L3MwSpfDJp4Q',
    appId: '1:839286460671:android:aa9a6037a55f346b647cca',
    messagingSenderId: '839286460671',
    projectId: 'finalyearproject-b2776',
    databaseURL: 'https://finalyearproject-b2776-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finalyearproject-b2776.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9o2ahgM39ir6DGYtKes-IP1aJ7liFYh8',
    appId: '1:839286460671:ios:908035f5e47a6bcc647cca',
    messagingSenderId: '839286460671',
    projectId: 'finalyearproject-b2776',
    databaseURL: 'https://finalyearproject-b2776-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finalyearproject-b2776.firebasestorage.app',
    iosBundleId: 'com.example.fypProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9o2ahgM39ir6DGYtKes-IP1aJ7liFYh8',
    appId: '1:839286460671:ios:908035f5e47a6bcc647cca',
    messagingSenderId: '839286460671',
    projectId: 'finalyearproject-b2776',
    databaseURL: 'https://finalyearproject-b2776-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finalyearproject-b2776.firebasestorage.app',
    iosBundleId: 'com.example.fypProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGnmSdcYDr9JKjo7ZeYAsYWycT0CfNCyI',
    appId: '1:839286460671:web:dcfa67bb73b01b71647cca',
    messagingSenderId: '839286460671',
    projectId: 'finalyearproject-b2776',
    authDomain: 'finalyearproject-b2776.firebaseapp.com',
    databaseURL: 'https://finalyearproject-b2776-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finalyearproject-b2776.firebasestorage.app',
    measurementId: 'G-2Q35W3YRBG',
  );
}
